cert_pem = "certs/data1-cert.pem"
key_pem = "certs/data1-key.pem"
trust_pem = "certs/data1-trust.pem"
gateway_addresses = [
    "/ip4/127.0.0.1/udp/8080/quic-v1"
]
listen_addresses = [
    "/ip4/127.0.0.1/udp/58040/quic-v1",
]
external_addresses = [
]
dataset_path = "mnist/mnist"
exclude_cidr = ["192.0.2.0/24"]
relay_circuit = true
telemetry_sampler = "parentbased_traceidratio"
telemetry_sample_ratio = 0.02

[network]
bandwidth_mbps = 1000
rtt_ms = 150
handshake_timeout = 30
